blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.home, name="home"),
    path("articles", views.articles, name="articles"),
    path("article/<int:article_id>", views.article, name="article"),
    path("find", views.find, name="find")
]

sassproj/urls.py
from django.contrib import admin
from django.urls import path, include

import blog

handler404 = "blog.views.custom404"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls"))
]

blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    authors = models.CharField(max_length=255)
    date = models.DateField()
    # invisible articles should still be viewable, just they do not show up on the listed articles page
    visible = models.BooleanField(default=True)
    

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404

from datetime import datetime

from .models import Article

# Create your views here.
def home(request):
    return render(request, "blog/home.html")

def articles(request):

    # only visible articles and past/current articles are processed
    articles = Article.objects.filter(visible=True, date__lte=datetime.today().date())

    return render(request, "blog/articles.html", {"articles": articles})

def article(request, article_id):
    current_article = get_object_or_404(Article, pk=article_id)
    if (current_article.date > datetime.today().date()):
        raise Http404
    paragraphs = current_article.body.split("\r\n")
    edited_paragraphs = ["#br" if paragraph=="" else paragraph for paragraph in paragraphs]
    return render(request, "blog/article.html", {"article": current_article, "paragraphs": edited_paragraphs})

def find(request):
    return render(request, "blog/find.html")

def custom404(request, exception):
    return render(request, "blog/404.html", status=404)

blog/templates/base.html
{% load compress %}
{% load static %}

<head>
    {% compress css %}
    <link rel="stylesheet" href="{% static 'style.css' %}" content="text/css">
    {% endcompress %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@700&family=Lora&display=swap" rel="stylesheet">
    <meta name="viewport" contents="height=device-height">
</head>
<body>
    
    <div class="header">
        {% comment %} <div class="navbutton"> X </div> {% endcomment %}
        <div></div>
        <div class="logo"><a class="nostyle logoelem" href="/"><h1>.Blog</h1></a></div>    

        <div class="links">
            <a href="{% url 'blog:home' %}" class="nostyle"><div class="hoverable element"><p>Home</p></div></a>
            <a href="{% url 'blog:articles' %}" class="nostyle"><div class="hoverable element"><p>Articles</p></div></a>
            <a href="{% url 'blog:find' %}" class="nostyle"><div class="element hoverable"><p>Find me</p></div></a>
            {% comment %} <a href="https://88potatoes.github.io/" class="nostyle"><div class="element">old</div></a>    {% endcomment %}
        </div>
    </div>
    {% comment %} <div class="sidebar">
        <a href="{% url 'blog:home' %}" class="nostyle"><div class="element">Home</div></a>
        <a href="{% url 'blog:articles' %}" class="nostyle"><div class="element">Articles</div></a>
        <a href="{% url 'blog:find' %}" class="nostyle"><div class="element">Find me</div></a>
        <a href="https://88potatoes.github.io/" class="nostyle"><div class="element">old</div></a>
    </div> {% endcomment %}
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
    <div class="footer"></div>
    
</body>

blog/templates/blog/article.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="top-band">
    <div class="title">
        <h1>{{ article.title }}</h1>
        <div class="lower">
            <div><h4>{{ article.authors }}</h4></div>
            <div><h4>{{ article.date }}</h4></div>
        </div>
    </div>
</div>
<div class="body">
<div class="paragraph-container">
{% for paragraph in paragraphs %}
    {% if paragraph == "#br" %}
        <br>
    {% elif '$img.' in paragraph %}
        {% with path=paragraph|slice:"5:" %}
        {% with img_path="images/"|add:path %}
            
            <img src={% static img_path %} alt="image">
        {% endwith %}
        {% endwith %}
    {% else %}
        <p>{{paragraph}}</p>
    {% endif %}
    
{% endfor %}
</div>
</div>
{% comment %} <p>{{ article.body }}</p> {% endcomment %}
{% endblock content %}

blog/templates/blog/articles.html
{% extends "base.html" %}

{% block content %}
<div class="article_container_outer">
    <div class="title">
        <h1 class="index">Articles</h1>
    </div>
    <div class="article_container">
        {% if not articles %}
            <div><p>No articles available</p></div>
        {% else %}
            {% for article in articles %}
                <a class="nostyle" href="{% url 'blog:article' article.id %}">
                    <div class="article">
                        <div></div>
                        <div class="middle-text"><h3>{{ article.title }}</h3></div>
                        <div class="high-text"><p>{{ article.date }}</p></div>
                    </div>
                </a>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content%}

blog/templates/blog/find.html
{% extends "base.html" %}

{% block content %}
<div class="home_container">
    <div><p>Find me at these links below.</p></div>
    <a href="https://www.linkedin.com/in/eric-lang-71b7ab237/" class="nostyle centered"><svg xmlns="http://www.w3.org/2000/svg" class="find_icon hoverable_svg" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg></a>
    <a href="https://github.com/88potatoes" class="nostyle centered"><svg xmlns="http://www.w3.org/2000/svg" class="find_icon hoverable_svg" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg></a>
</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="home_container">
    <img src="{% static 'images/IMG_ME.webp' %}" id="profile">
    <div><p>Hey it's Eric. Welcome to my blog!</p></div>
    <div><p>Dive right in</p></div>
    <a href="/" class="nostyle"><div class="hoverable element random_button"><p>Random article</p></div></a>
</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="index">Index page</h1>
        
<h2> index page content</h2>
<div class="article_container">
    {% for article in articles %}
        <a class="nostyle" href="{% url 'blog:article' article.id %}">
            <div class="article">
                <h3>{{ title }}</h3>
                <p>{{ article.body }}</p>
                <p>{{ article.id }}</p>
            </div>
        </a>
    {% endfor %}
</div>
{% endblock content%}